value uialertview_getAlertViewStyle(value tag);
value uialertview_getDelegate(value tag);
value uialertview_getMessage(value tag);
value uialertview_getTitle(value tag);
value uialertview_getVisible(value tag);
void uialertview_show(value tag);
value uibutton_getAdjustsImageWhenDisabled(value tag);
value uibutton_getAdjustsImageWhenHighlighted(value tag);
value uibutton_getCurrentTitle(value tag);
value uibutton_getReversesTitleShadowWhenHighlighted(value tag);
value uibutton_getShowsTouchWhenHighlighted(value tag);
value uibutton_getTitleLabel(value tag);
value uibutton_backgroundRectForBounds(value tag, value arg1);
value uibutton_contentRectForBounds(value tag, value arg1);
value uibutton_imageRectForContentRect(value tag, value arg1);
void uibutton_setTitle(value tag, value arg1, value arg2);
value uibutton_titleForState(value tag, value arg1);
value uibutton_titleRectForContentRect(value tag, value arg1);
value uicollectionreusableview_getReuseIdentifier(value tag);
void uicollectionreusableview_prepareForReuse(value tag);
value uicollectionview_getAllowsMultipleSelection(value tag);
value uicollectionview_getAllowsSelection(value tag);
value uicollectionview_getBackgroundView(value tag);
void uicollectionview_reloadData(value tag);
value uicollectionviewcell_getBackgroundView(value tag);
value uicollectionviewcell_getContentView(value tag);
value uicollectionviewcell_getHighlighted(value tag);
value uicollectionviewcell_getSelected(value tag);
value uicollectionviewcell_getSelectedBackgroundView(value tag);
value uicontrol_getEnabled(value tag);
value uicontrol_getHighlighted(value tag);
value uicontrol_getSelected(value tag);
value uicontrol_getTouchInside(value tag);
value uicontrol_getTracking(value tag);
value uiimageview_getHighlighted(value tag);
value uiimageview_isAnimating(value tag);
void uiimageview_startAnimating(value tag);
void uiimageview_stopAnimating(value tag);
value uilabel_getAdjustsFontSizeToFitWidth(value tag);
value uilabel_getAdjustsLetterSpacingToFitWidth(value tag);
value uilabel_getEnabled(value tag);
value uilabel_getHighlighted(value tag);
value uilabel_getText(value tag);
void uilabel_drawTextInRect(value tag, value arg1);
value uipagecontrol_getDefersCurrentPageDisplay(value tag);
value uipagecontrol_getHidesForSinglePage(value tag);
void uipagecontrol_updateCurrentPageDisplay(value tag);
value uipickerview_getShowsSelectionIndicator(value tag);
void uipickerview_reloadAllComponents(value tag);
value uirefreshcontrol_getRefreshing(value tag);
void uirefreshcontrol_beginRefreshing(value tag);
void uirefreshcontrol_endRefreshing(value tag);
value uiresponder_becomeFirstResponder(value tag);
value uiresponder_canBecomeFirstResponder(value tag);
value uiresponder_canResignFirstResponder(value tag);
value uiresponder_isFirstResponder(value tag);
void uiresponder_reloadInputViews(value tag);
value uiresponder_resignFirstResponder(value tag);
value uiscrollview_getAlwaysBounceHorizontal(value tag);
value uiscrollview_getAlwaysBounceVertical(value tag);
value uiscrollview_getBounces(value tag);
value uiscrollview_getBouncesZoom(value tag);
value uiscrollview_getCanCancelContentTouches(value tag);
value uiscrollview_getDecelerating(value tag);
value uiscrollview_getDelaysContentTouches(value tag);
value uiscrollview_getDirectionalLockEnabled(value tag);
value uiscrollview_getDragging(value tag);
value uiscrollview_getPagingEnabled(value tag);
value uiscrollview_getScrollEnabled(value tag);
value uiscrollview_getScrollsToTop(value tag);
value uiscrollview_getShowsHorizontalScrollIndicator(value tag);
value uiscrollview_getShowsVerticalScrollIndicator(value tag);
value uiscrollview_getTracking(value tag);
value uiscrollview_getZoomBouncing(value tag);
value uiscrollview_getZooming(value tag);
void uiscrollview_flashScrollIndicators(value tag);
void uiscrollview_scrollRectToVisible(value tag, value arg1, value arg2);
value uiscrollview_touchesShouldCancelInContentView(value tag, value tag1);
void uiscrollview_zoomToRect(value tag, value arg1, value arg2);
value uisearchbar_getPlaceholder(value tag);
value uisearchbar_getPrompt(value tag);
value uisearchbar_getSearchResultsButtonSelected(value tag);
value uisearchbar_getShowsBookmarkButton(value tag);
value uisearchbar_getShowsCancelButton(value tag);
value uisearchbar_getShowsScopeBar(value tag);
value uisearchbar_getShowsSearchResultsButton(value tag);
value uisearchbar_getText(value tag);
value uisearchbar_getTranslucent(value tag);
value uisegmentedcontrol_getApportionsSegmentWidthsByContent(value tag);
value uisegmentedcontrol_getMomentary(value tag);
void uisegmentedcontrol_removeAllSegments(value tag);
value uislider_getContinuous(value tag);
value uislider_maximumValueImageRectForBounds(value tag, value arg1);
value uislider_minimumValueImageRectForBounds(value tag, value arg1);
value uislider_trackRectForBounds(value tag, value arg1);
value uistepper_getAutorepeat(value tag);
value uistepper_getContinuous(value tag);
value uistepper_getWraps(value tag);
value uiswitch_getOn(value tag);
value uitabbar_endCustomizingAnimated(value tag, value arg1);
value uitabbar_isCustomizing(value tag);
value uitableview_getAllowsMultipleSelection(value tag);
value uitableview_getAllowsMultipleSelectionDuringEditing(value tag);
value uitableview_getAllowsSelection(value tag);
value uitableview_getAllowsSelectionDuringEditing(value tag);
value uitableview_getBackgroundView(value tag);
value uitableview_getEditing(value tag);
value uitableview_getTableFooterView(value tag);
value uitableview_getTableHeaderView(value tag);
void uitableview_beginUpdates(value tag);
value uitableview_dequeueReusableCellWithIdentifier(value tag, value arg1);
value uitableview_dequeueReusableHeaderFooterViewWithIdentifier(value tag, value arg1);
void uitableview_endUpdates(value tag);
void uitableview_reloadData(value tag);
void uitableview_reloadSectionIndexTitles(value tag);
value uitableviewcell_getBackgroundView(value tag);
value uitableviewcell_getContentView(value tag);
value uitableviewcell_getDetailTextLabel(value tag);
value uitableviewcell_getEditing(value tag);
value uitableviewcell_getEditingAccessoryView(value tag);
value uitableviewcell_getMultipleSelectionBackgroundView(value tag);
value uitableviewcell_getReuseIdentifier(value tag);
value uitableviewcell_getSelected(value tag);
value uitableviewcell_getSelectedBackgroundView(value tag);
value uitableviewcell_getShouldIndentWhileEditing(value tag);
value uitableviewcell_getShowingDeleteConfirmation(value tag);
value uitableviewcell_getShowsReorderControl(value tag);
value uitableviewcell_getTextLabel(value tag);
void uitableviewcell_prepareForReuse(value tag);
void uitableviewcell_setHighlighted(value tag, value arg1, value arg2);
value uitableviewheaderfooterview_getBackgroundView(value tag);
value uitableviewheaderfooterview_getContentView(value tag);
value uitableviewheaderfooterview_getDetailTextLabel(value tag);
value uitableviewheaderfooterview_getReuseIdentifier(value tag);
value uitableviewheaderfooterview_getTextLabel(value tag);
void uitableviewheaderfooterview_prepareForReuse(value tag);
value uitextfield_getAdjustsFontSizeToFitWidth(value tag);
value uitextfield_getAllowsEditingTextAttributes(value tag);
value uitextfield_getClearsOnBeginEditing(value tag);
value uitextfield_getClearsOnInsertion(value tag);
value uitextfield_getEditing(value tag);
value uitextfield_getLeftView(value tag);
value uitextfield_getPlaceholder(value tag);
value uitextfield_getRightView(value tag);
value uitextfield_getText(value tag);
value uitextfield_borderRectForBounds(value tag, value arg1);
value uitextfield_clearButtonRectForBounds(value tag, value arg1);
void uitextfield_drawPlaceholderInRect(value tag, value arg1);
void uitextfield_drawTextInRect(value tag, value arg1);
value uitextfield_editingRectForBounds(value tag, value arg1);
value uitextfield_leftViewRectForBounds(value tag, value arg1);
value uitextfield_placeholderRectForBounds(value tag, value arg1);
value uitextfield_rightViewRectForBounds(value tag, value arg1);
value uitextfield_textRectForBounds(value tag, value arg1);
value uitextview_getAllowsEditingTextAttributes(value tag);
value uitextview_getClearsOnInsertion(value tag);
value uitextview_getEditable(value tag);
value uitextview_getText(value tag);
value uitextview_hasText(value tag);
value uiview_getAutoresizesSubviews(value tag);
value uiview_getBounds(value tag);
value uiview_getClearsContextBeforeDrawing(value tag);
value uiview_getClipsToBounds(value tag);
value uiview_getExclusiveTouch(value tag);
value uiview_getFrame(value tag);
value uiview_getHidden(value tag);
value uiview_getMultipleTouchEnabled(value tag);
value uiview_getOpaque(value tag);
value uiview_getRestorationIdentifier(value tag);
value uiview_getSuperview(value tag);
value uiview_getUserInteractionEnabled(value tag);
void uiview_addSubview(value tag, value tag1);
value uiview_alignmentRectForFrame(value tag, value arg1);
void uiview_bringSubviewToFront(value tag, value tag1);
void uiview_didAddSubview(value tag, value tag1);
void uiview_didMoveToSuperview(value tag);
void uiview_didMoveToWindow(value tag);
void uiview_drawRect(value tag, value arg1);
value uiview_endEditing(value tag, value arg1);
void uiview_exerciseAmbiguityInLayout(value tag);
value uiview_frameForAlignmentRect(value tag, value arg1);
value uiview_hasAmbiguousLayout(value tag);
void uiview_insertSubview(value tag, value tag1, value tag2);
void uiview_insertSubview2(value tag, value tag1, value tag2);
void uiview_invalidateIntrinsicContentSize(value tag);
value uiview_isDescendantOfView(value tag, value tag1);
void uiview_layoutIfNeeded(value tag);
void uiview_layoutSubviews(value tag);
value uiview_needsUpdateConstraints(value tag);
void uiview_removeFromSuperview(value tag);
void uiview_sendSubviewToBack(value tag, value tag1);
void uiview_setNeedsDisplay(value tag);
void uiview_setNeedsDisplayInRect(value tag, value arg1);
void uiview_setNeedsLayout(value tag);
void uiview_setNeedsUpdateConstraints(value tag);
void uiview_setTranslatesAutoresizingMaskIntoConstraints(value tag, value arg1);
void uiview_sizeToFit(value tag);
value uiview_translatesAutoresizingMaskIntoConstraints(value tag);
void uiview_updateConstraints(value tag);
void uiview_updateConstraintsIfNeeded(value tag);
value uiview_viewForBaselineLayout(value tag);
void uiview_willMoveToSuperview(value tag, value tag1);
void uiview_willRemoveSubview(value tag, value tag1);
value uiwebview_getCanGoBack(value tag);
value uiwebview_getCanGoForward(value tag);
value uiwebview_getKeyboardDisplayRequiresUserAction(value tag);
value uiwebview_getLoading(value tag);
value uiwebview_getMediaPlaybackAllowsAirPlay(value tag);
value uiwebview_getMediaPlaybackRequiresUserAction(value tag);
value uiwebview_getScalesPageToFit(value tag);
value uiwebview_getSuppressesIncrementalRendering(value tag);
void uiwebview_goBack(value tag);
void uiwebview_goForward(value tag);
void uiwebview_reload(value tag);
void uiwebview_stopLoading(value tag);
value uiwebview_stringByEvaluatingJavaScriptFromString(value tag, value arg1);
value uiwindow_getKeyWindow(value tag);
void uiwindow_becomeKeyWindow(value tag);
void uiwindow_makeKeyAndVisible(value tag);
void uiwindow_makeKeyWindow(value tag);
void uiwindow_resignKeyWindow(value tag);
void initUIViewEventListeners(int tag);
void initUIButtonEventListeners(int tag);
void initUIResponderEventListeners(int tag);
void initUILabelEventListeners(int tag);
void initUIImageViewEventListeners(int tag);
void initMKMapViewEventListeners(int tag);
void initUIAlertViewEventListeners(int tag);
void initUICollectionReusableViewEventListeners(int tag);
void initUICollectionViewEventListeners(int tag);
void initUICollectionViewCellEventListeners(int tag);
void initUIDatePickerEventListeners(int tag);
void initUINavigationBarEventListeners(int tag);
void initUIPageControlEventListeners(int tag);
void initUIPickerViewEventListeners(int tag);
void initUIPopoverBackgroundViewEventListeners(int tag);
void initUIProgressViewEventListeners(int tag);
void initUIRefreshControlEventListeners(int tag);
void initUIScrollViewEventListeners(int tag);
void initUISearchBarEventListeners(int tag);
void initUISegmentedControlEventListeners(int tag);
void initUISliderEventListeners(int tag);
void initUIStepperEventListeners(int tag);
void initUISwitchEventListeners(int tag);
void initUITabBarEventListeners(int tag);
void initUITableViewEventListeners(int tag);
void initUITableViewCellEventListeners(int tag);
void initUITableViewHeaderFooterViewEventListeners(int tag);
void initUITextViewEventListeners(int tag);
void initUIWebViewEventListeners(int tag);
void initUIWindowEventListeners(int tag);
void initUIControlEventListeners(int tag);
void initUITextFieldEventListeners(int tag);
