value uialertview_textFieldAtIndex(value tag, value arg1);
void uialertview_show(value tag);
void uialertview_showWithAnimationType(value tag, value arg1);
void uialertview_dismissWithClickedButtonIndex(value tag, value arg1, value arg2);
value uialertview_getAlertViewStyle(value tag);
value uialertview_getFirstOtherButtonIndex(value tag);
value uialertview_getCancelButtonIndex(value tag);
value uialertview_defaultButtonIndex(value tag);
void uialertview_setDefaultButtonIndex(value tag, value arg1);
value uialertview_getVisible(value tag);
value uialertview_getNumberOfButtons(value tag);
value uialertview_buttonTitleAtIndex(value tag, value arg1);
value uialertview_addButtonWithTitle(value tag, value tag1);
value uialertview_getMessage(value tag);
value uialertview_getTitle(value tag);
value uialertview_getDelegate(value tag);
void uialertview_removeFromSuperview(value tag);
value uialertview_becomeFirstResponder(value tag);
void uialertview_replaceAlert(value tag, value tag1);
void uialertview_presentSheetFromButtonBar(value tag, value tag1);
void uialertview_layout(value tag);
value uialertview_numberOfLinesInTitle(value tag);
value uialertview_runsModal(value tag);
void uialertview_setRunsModal(value tag, value arg1);
value uialertview_blocksInteraction(value tag);
void uialertview_setBlocksInteraction(value tag, value arg1);
value uialertview_suspendTag(value tag);
void uialertview_setSuspendTag(value tag, value arg1);
value uialertview_dimsBackground(value tag);
void uialertview_setDimsBackground(value tag, value arg1);
void uialertview_setAlertSheetStyle(value tag, value arg1);
value uialertview_forceHorizontalButtonsLayout(value tag);
void uialertview_setForceHorizontalButtonsLayout(value tag, value arg1);
value uialertview_alertSheetStyle(value tag);
value uialertview_numberOfRows(value tag);
void uialertview_setNumberOfRows(value tag, value arg1);
void uialertview_dismissAnimated(value tag, value arg1);
void uialertview_dismiss(value tag);
void uialertview_setDimView(value tag, value tag1);
void uialertview_presentSheetToAboveView(value tag, value tag1);
void uialertview_presentSheetInView(value tag, value tag1);
void uialertview_presentSheetFromAboveView(value tag, value tag1);
void uialertview_presentSheetFromBehindView(value tag, value tag1);
void uialertview_popupAlertAnimated(value tag, value arg1);
void uialertview_popupAlertAnimated2(value tag, value arg1, value arg2);
value uialertview_isBodyTextTruncated(value tag);
void uialertview_layoutAnimated(value tag, value arg1);
value uialertview_taglineTextLabel(value tag);
value uialertview_bodyTextLabel(value tag);
value uialertview_titleLabel(value tag);
value uialertview_showsOverSpringBoardAlerts(value tag);
void uialertview_setShowsOverSpringBoardAlerts(value tag, value arg1);
value uialertview_tableView(value tag);
value uialertview_tableShouldShowMinimumContent(value tag);
void uialertview_setTableShouldShowMinimumContent(value tag, value arg1);
value uialertview_context(value tag);
void uialertview_setContext(value tag, value tag1);
value uialertview_buttonCount(value tag);
value uialertview_addButtonWithTitle2(value tag, value tag1, value tag2);
value uialertview_destructiveButton(value tag);
void uialertview_setDestructiveButton(value tag, value tag1);
value uialertview_buttonAtIndex(value tag, value arg1);
value uialertview_defaultButton(value tag);
void uialertview_setDefaultButton(value tag, value tag1);
value uialertview_keyboard(value tag);
void uialertview_setKeyboardShowsOnPopup(value tag, value arg1);
value uialertview_textField(value tag);
value uialertview_textFieldCount(value tag);
value uialertview_bodyMaxLineCount(value tag);
void uialertview_setBodyTextMaxLineCount(value tag, value arg1);
value uialertview_titleMaxLineCount(value tag);
void uialertview_setTitleMaxLineCount(value tag, value arg1);
value uialertview_bodyText(value tag);
value uialertview_subtitle(value tag);
void uialertview_setSubtitle(value tag, value tag1);
void uialertview_setTaglineText(value tag, value tag1);
void uialertview_setBodyText(value tag, value tag1);
value uialertview_buttons(value tag);
value uialertview_requiresPortraitOrientation(value tag);
void uialertview_setGroupsTextFields(value tag, value arg1);
value uialertview_groupsTextFields(value tag);
value uialertview_addTextFieldWithValue(value tag, value tag1, value tag2);
value uibutton_getCurrentTitle(value tag);
value uibutton_attributedTitleForState(value tag, value arg1);
value uibutton_backgroundImageForState(value tag, value arg1);
value uibutton_imageForState(value tag, value arg1);
value uibutton_titleShadowColorForState(value tag, value arg1);
value uibutton_titleColorForState(value tag, value arg1);
value uibutton_titleForState(value tag, value arg1);
void uibutton_setAttributedTitle(value tag, value tag1, value arg2);
void uibutton_setBackgroundImage(value tag, value tag1, value arg2);
void uibutton_setImage(value tag, value tag1, value arg2);
void uibutton_setTitleShadowColor(value tag, value tag1, value arg2);
void uibutton_setTitleColor(value tag, value tag1, value arg2);
void uibutton_setTitle(value tag, value arg1, value arg2);
value uibutton_getTitleLabel(value tag);
value uibutton_getShowsTouchWhenHighlighted(value tag);
value uibutton_getAdjustsImageWhenDisabled(value tag);
value uibutton_getAdjustsImageWhenHighlighted(value tag);
value uibutton_getReversesTitleShadowWhenHighlighted(value tag);
value uibutton_getButtonType(value tag);
value uibutton_getLineBreakMode(value tag);
value uibutton_image(value tag);
void uibutton_setTitle2(value tag, value arg1);
value uibutton_title(value tag);
void uibutton_crossfadeToImage(value tag, value tag1, value arg2);
void uibutton_setBackgroundImage2(value tag, value tag1, value arg2);
void uibutton_setImage2(value tag, value tag1, value arg2);
void uibutton_setTitleShadowColor2(value tag, value tag1, value arg2);
void uibutton_setTitleColor2(value tag, value tag1, value arg2);
void uibutton_setTitle3(value tag, value arg1, value arg2);
void uibutton_setShowPressFeedback(value tag, value arg1);
void uibutton_setDisabledDimsImage(value tag, value arg1);
value uibutton_autosizesToFit(value tag);
void uibutton_setAutosizesToFit(value tag, value arg1);
void uicontrol_sendActionsForControlEvents(value tag, value arg1);
value uicontrol_actionsForTarget(value tag, value tag1, value arg2);
value uicontrol_allTargets(value tag);
value uicontrol_getSelected(value tag);
value uicontrol_getContentHorizontalAlignment(value tag);
value uicontrol_getContentVerticalAlignment(value tag);
value uicontrol_getHighlighted(value tag);
void uicontrol_cancelTrackingWithEvent(value tag, value tag1);
void uicontrol_endTrackingWithTouch(value tag, value tag1, value tag2);
value uicontrol_continueTrackingWithTouch(value tag, value tag1, value tag2);
value uicontrol_beginTrackingWithTouch(value tag, value tag1, value tag2);
value uicontrol_getTouchInside(value tag);
value uicontrol_getState(value tag);
value uicontrol_getTracking(value tag);
void uicontrol_setTracking(value tag, value arg1);
void uicontrol_removeTarget(value tag, value tag1, value arg2);
value uicontrol_hasOneOrMoreTargets(value tag);
value uicontrol_requiresDisplayOnTracking(value tag);
void uicontrol_setRequiresDisplayOnTracking(value tag, value arg1);
value uicontrol_touchDragged(value tag);
value uicontrol_shouldTrack(value tag);
value uicontrol_mouseInside(value tag);
value uiimageview_getAnimationRepeatCount(value tag);
value uiimageview_isAnimating(value tag);
void uiimageview_stopAnimating(value tag);
void uiimageview_startAnimating(value tag);
value uiimageview_getHighlighted(value tag);
void uiimageview_setAnimating(value tag, value arg1);
value uiimageview_useBlockyMagnificationInClassic(value tag);
value uilabel_drawsUnderline(value tag);
void uilabel_setDrawsUnderline(value tag, value arg1);
value uilabel_letterpressStyle(value tag);
void uilabel_setLetterpressStyle(value tag, value tag1);
value uilabel_drawsLetterpress(value tag);
void uilabel_setDrawsLetterpress(value tag, value arg1);
void uilabel_setMarqueeRunning(value tag, value arg1);
value uilabel_marqueeRunning(value tag);
void uilabel_setMarqueeEnabled(value tag, value arg1);
void uilabel_drawTextInRect(value tag, value arg1);
value uilabel_getBaselineAdjustment(value tag);
value uilabel_getAdjustsLetterSpacingToFitWidth(value tag);
value uilabel_getNumberOfLines(value tag);
value uilabel_getLineBreakMode(value tag);
value uilabel_getHighlighted(value tag);
value uilabel_currentTextColor(value tag);
value uilabel_getTextAlignment(value tag);
value uilabel_getAdjustsFontSizeToFitWidth(value tag);
value uilabel_getText(value tag);
value uilabel_isTextFieldCenteredLabel(value tag);
void uilabel_drawContentsInRect(value tag, value arg1);
value uilabel_centersHorizontally(value tag);
void uilabel_setCentersHorizontally(value tag, value arg1);
value uilabel_color(value tag);
void uilabel_setColor(value tag, value tag1);
value uilabel_autotrackTextToFit(value tag);
void uilabel_setAutotrackTextToFit(value tag, value arg1);
value uiresponder_firstResponder(value tag);
value uiresponder_isFirstResponder(value tag);
value uiresponder_becomeFirstResponder(value tag);
void uiresponder_remoteControlReceivedWithEvent(value tag, value tag1);
void uiresponder_motionCancelled(value tag, value arg1, value tag2);
void uiresponder_motionEnded(value tag, value arg1, value tag2);
void uiresponder_motionBegan(value tag, value arg1, value tag2);
void uiresponder_reloadInputViewsWithoutReset(value tag);
void uiresponder_reloadInputViews(value tag);
value uiresponder_nextFirstResponder(value tag);
value uiresponder_defaultFirstResponder(value tag);
value uitextfield_getRightViewMode(value tag);
value uitextfield_getRightView(value tag);
value uitextfield_getLeftViewMode(value tag);
value uitextfield_getLeftView(value tag);
value uitextfield_getClearButtonMode(value tag);
value uitextfield_getBorderStyle(value tag);
void uitextfield_setSelectionGranularity(value tag, value arg1);
value uitextfield_selectionGranularity(value tag);
void uitextfield_setBaseWritingDirection(value tag, value arg1, value tag2);
value uitextfield_baseWritingDirectionForPosition(value tag, value tag1, value arg2);
value uitextfield_characterRangeByExtendingPosition(value tag, value tag1, value arg2);
value uitextfield_positionWithinRange(value tag, value tag1, value arg2);
value uitextfield_offsetFromPosition(value tag, value tag1, value tag2);
value uitextfield_comparePosition(value tag, value tag1, value tag2);
value uitextfield_positionFromPosition(value tag, value tag1, value arg2, value arg3);
value uitextfield_positionFromPosition2(value tag, value tag1, value arg2);
value uitextfield_textRangeFromPosition(value tag, value tag1, value tag2);
void uitextfield_unmarkText(value tag);
void uitextfield_replaceRange(value tag, value tag1, value tag2);
value uitextfield_textInRange(value tag, value tag1);
value uitextfield_hasText(value tag);
value uitextfield_metadataDictionariesForDictationResults(value tag);
void uitextfield_removeDictationResultPlaceholder(value tag, value tag1, value arg2);
value uitextfield_insertDictationResultPlaceholder(value tag);
void uitextfield_insertDictationResult(value tag, value tag1, value tag2);
void uitextfield_insertText(value tag, value tag1);
void uitextfield_deleteBackward(value tag);
value uitextfield_inPopover(value tag);
void uitextfield_replace(value tag, value tag1);
void uitextfield_toggleUnderline(value tag, value tag1);
void uitextfield_toggleItalics(value tag, value tag1);
void uitextfield_toggleBoldface(value tag, value tag1);
void uitextfield_makeTextWritingDirectionLeftToRight(value tag, value tag1);
void uitextfield_makeTextWritingDirectionRightToLeft(value tag, value tag1);
void uitextfield_selectAll(value tag, value tag1);
void uitextfield_select(value tag, value tag1);
void uitextfield_paste(value tag, value tag1);
void uitextfield_copy(value tag, value tag1);
void uitextfield_cut(value tag, value tag1);
value uitextfield_webView(value tag);
value uitextfield_selectedAttributedText(value tag);
value uitextfield_selectedText(value tag);
value uitextfield_selectionRectsForRange(value tag, value tag1);
value uitextfield_selectionView(value tag);
void uitextfield_cancelAutoscroll(value tag);
value uitextfield_hasSelection(value tag);
value uitextfield_isEditable(value tag);
value uitextfield_undoManager(value tag);
value uitextfield_atomStyle(value tag);
void uitextfield_setAtomStyle(value tag, value arg1);
value uitextfield_drawsAsAtom(value tag);
void uitextfield_setDrawsAsAtom(value tag, value arg1);
value uitextfield_isUndoEnabled(value tag);
void uitextfield_setUndoEnabled(value tag, value arg1);
void uitextfield_setTextCentersVertically(value tag, value arg1);
void uitextfield_setTextCentersHorizontally(value tag, value arg1);
void uitextfield_setLabel(value tag, value tag1);
value uitextfield_textLabel(value tag);
value uitextfield_hasMarkedText(value tag);
void uitextfield_setBecomesFirstResponderOnClearButtonTap(value tag, value arg1);
void uitextfield_setIcon(value tag, value tag1);
void uitextfield_clearText(value tag);
void uitextfield_layoutTilesNow(value tag);
void uitextfield_selectAll2(value tag);
void uitextfield_setInactiveHasDimAppearance(value tag, value arg1);
void uitextfield_setTextFont(value tag, value tag1);
void uitextfield_drawBorder(value tag, value arg1);
void uitextfield_setClearButtonStyle(value tag, value arg1);
void uitextfield_setTextAutorresizesToFit(value tag, value arg1);
void uitextfield_setAutoresizesTextToFit(value tag, value arg1);
value uitextfield_documentFragmentForPasteboardItemAtIndex(value tag, value arg1);
value uitextfield_supportedPasteboardTypesForCurrentSelection(value tag);
value uitextfield_fieldEditor(value tag, value tag1, value tag2);
void uitextfield_fieldEditorDidChangeSelection(value tag, value tag1);
void uitextfield_selectAllFromFieldEditor(value tag, value tag1);
void uitextfield_fieldEditorDidChange(value tag, value tag1);
value uitextfield_customOverlayContainer(value tag);
void uitextfield_keyboardInputChangedSelection(value tag, value tag1);
value uitextfield_keyboardInputChanged(value tag, value tag1);
value uitextfield_keyboardInputShouldDelete(value tag, value tag1);
value uitextfield_keyboardInput(value tag, value tag1, value tag2, value arg3);
void uitextfield_willDetachFieldEditor(value tag, value tag1);
void uitextfield_attachFieldEditor(value tag, value tag1);
void uitextfield_willAttachFieldEditor(value tag, value tag1);
void uitextfield_drawPrefixInRect(value tag, value arg1);
void uitextfield_drawSuffixInRect(value tag, value arg1);
void uitextfield_drawPlaceholderInRect(value tag, value arg1);
void uitextfield_drawTextInRect(value tag, value arg1);
value uitextfield_getAllowsEditingTextAttributes(value tag);
value uitextfield_getAdjustsFontSizeToFitWidth(value tag);
void uitextfield_setClearsPlaceholderOnBeginEditing(value tag, value arg1);
value uitextfield_clearsPlaceholderOnBeginEditing(value tag);
value uitextfield_getClearsOnBeginEditing(value tag);
value uitextfield_getPlaceholder(value tag);
void uitextfield_createPlaceholderIfNecessary(value tag);
void uitextfield_finishedSettingPlaceholder(value tag);
value uitextfield_createTextLabelWithTextColor(value tag, value tag1);
value uitextfield_createPlaceholderLabelWithFont(value tag, value tag1, value arg2);
value uitextfield_getTextAlignment(value tag);
void uitextfield_disableClearsOnInsertion(value tag);
value uitextfield_getClearsOnInsertion(value tag);
value uitextfield_shadowColor(value tag);
void uitextfield_setShadowColor(value tag, value tag1);
value uitextfield_getText(value tag);
void uitextfield_finishedSettingTextOrAttributedText(value tag);
value uitextfield_searchText(value tag);
value uitextfield_getSecureTextEntry(value tag);
void uitextfield_forwardInvocation(value tag, value tag1);
value uitextfield_textInputTraits(value tag);
value uitextfield_actualFont(value tag);
value uitextfield_clearButton(value tag);
void uitextfield_setAnimating(value tag, value arg1);
value uitextfield_getAutocapitalizationType(value tag);
value uitextfield_getAutocorrectionType(value tag);
value uitextfield_getEnablesReturnKeyAutomatically(value tag);
value uitextfield_getKeyboardAppearance(value tag);
value uitextfield_getKeyboardType(value tag);
value uitextfield_getReturnKeyType(value tag);
value uitextfield_getSpellCheckingType(value tag);
value uiview_getTag(value tag);
value uiview_getSuperview(value tag);
value uiview_getFrame(value tag);
value uiview_getBounds(value tag);
value uiview_getClipsToBounds(value tag);
value uiview_getExclusiveTouch(value tag);
value uiview_getMultipleTouchEnabled(value tag);
value uiview_getOpaque(value tag);
void uiview_sizeToFit(value tag);
value uiview_autoresizesSubviews(value tag);
void uiview_layoutIfNeeded(value tag);
void uiview_setNeedsLayout(value tag);
value uiview_viewWithTag(value tag, value arg1);
value uiview_isDescendantOfView(value tag, value tag1);
void uiview_insertSubview(value tag, value tag1, value arg2);
void uiview_insertSubview2(value tag, value tag1, value tag2);
void uiview_insertSubview3(value tag, value tag1, value tag2);
void uiview_didMoveToWindow(value tag);
void uiview_didMoveToSuperview(value tag);
void uiview_willMoveToSuperview(value tag, value tag1);
void uiview_willRemoveSubview(value tag, value tag1);
void uiview_didAddSubview(value tag, value tag1);
void uiview_sendSubviewToBack(value tag, value tag1);
void uiview_bringSubviewToFront(value tag, value tag1);
void uiview_addSubview(value tag, value tag1);
void uiview_exchangeSubviewAtIndex(value tag, value arg1, value arg2);
void uiview_removeFromSuperview(value tag);
value uiview_clearsContextBeforeDrawing(value tag);
void uiview_setNeedsDisplayInRect(value tag, value arg1);
void uiview_setNeedsDisplay(value tag);
void uiview_drawRect(value tag, value arg1);
void uiview_removeAllGestureRecognizers(value tag);
value uiview_endEditing(value tag, value arg1);
void uiview_exerciseAmbiguityInLayout(value tag);
value uiview_hasAmbiguousLayout(value tag);
void uiview_updateConstraintsIfNeeded(value tag);
void uiview_setTranslatesAutoresizingMaskIntoConstraints(value tag, value arg1);
value uiview_translatesAutoresizingMaskIntoConstraints(value tag);
void uiview_setNeedsUpdateConstraints(value tag);
value uiview_needsUpdateConstraints(value tag);
void initUIViewEventListeners(int tag);
void initUIButtonEventListeners(int tag);
void initUIResponderEventListeners(int tag);
void initUILabelEventListeners(int tag);
void initUIImageViewEventListeners(int tag);
void initMKMapViewEventListeners(int tag);
void initUIAlertViewEventListeners(int tag);
void initUICollectionReusableViewEventListeners(int tag);
void initUICollectionViewEventListeners(int tag);
void initUICollectionViewCellEventListeners(int tag);
void initUIDatePickerEventListeners(int tag);
void initUINavigationBarEventListeners(int tag);
void initUIPageControlEventListeners(int tag);
void initUIPickerViewEventListeners(int tag);
void initUIPopoverBackgroundViewEventListeners(int tag);
void initUIProgressViewEventListeners(int tag);
void initUIRefreshControlEventListeners(int tag);
void initUIScrollViewEventListeners(int tag);
void initUISearchBarEventListeners(int tag);
void initUISegmentedControlEventListeners(int tag);
void initUISliderEventListeners(int tag);
void initUIStepperEventListeners(int tag);
void initUISwitchEventListeners(int tag);
void initUITabBarEventListeners(int tag);
void initUITableViewEventListeners(int tag);
void initUITableViewCellEventListeners(int tag);
void initUITableViewHeaderFooterViewEventListeners(int tag);
void initUITextViewEventListeners(int tag);
void initUIWebViewEventListeners(int tag);
void initUIWindowEventListeners(int tag);
void initUIControlEventListeners(int tag);
void initUITextFieldEventListeners(int tag);
